### ISSUE TITLE
Is the behavior of `push-to-back` and `bring-to-front` swapped?

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#101]
# Repro steps

1. Download, unzip, and open [layering demo.box.zip](https://github.com/user-attachments/files/16120003/layering.demo.box.zip)
2. Run `tell circle bring-to-front`

**Expected result**: The circle is rendered on top of the square. The square is not visible.

**Actual result**: The circle is rendered behind the square. Both the circle and square are visible. Screenshot:
<img width="472" alt="image" src="https://github.com/boxer-project/boxer-sunrise/assets/199935/50a35da5-4cd0-4ec1-91c3-69d1578da770">

# Missing reference documentation
`push-to-back` and `bring-to-front` aren't mentioned in [Boxer Manual V2](https://boxer-project.github.io/docs/Boxer%20Manual%20V2.pdf) so I'm inferring their expected behavior entirely from their names.

**Comment by sgithens** [comment]
Yes, the behavior of these is weird and not totally documented.  It's sort of been on the todo list to reform for a bit, and maybe add a few other niceties.  I'll keep this ticket in hand for that work.

**Comment by sgithens** [comment]
Fixed in cee88662ec63c6efdc74ae5ecd6e77482a505991 will be in v3.4.21

**Comment by sgithens** [comment]
Verified on v3.4.21 and closing.
