### ISSUE TITLE
`set-pen-color` ignores transparency value when given a data box

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#111]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`.

1. Download, unzip, and open [set-pen-color opacity repro.box.zip](https://github.com/user-attachments/files/16386663/set-pen-color.opacity.repro.box.zip)
2. Execute these consecutive lines:
    - `set-pen-color ...`
    - `pen-color`

**Expected result**: `pen-color` returns a semi-transparent blue:
<img width="63" alt="image" src="https://github.com/user-attachments/assets/3b32e4d9-5744-42ca-85ea-dde39e985ade">

**Actual result**: `pen-color` returns a blue without any transparency:
<img width="65" alt="image" src="https://github.com/user-attachments/assets/5dc053fc-cc98-435f-83a1-4596833cffb5">

Screenshot:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/f01ba649-4270-4a3f-aa9e-a05341745b06">

**Comment by sgithens** [comment]
This is fixed now in 299885d and will be in the 3.4.20 build. Leaving open until verified against build.

**Comment by rigdern** [comment]
I confirmed this no longer repros in Boxer version `3.4.20 2024-08-06`
