### ISSUE TITLE
The backmost rather than the frontmost sprite receives the click event

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#113]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`

1. Download, unzip, and open [click ordering repro.box.zip](https://github.com/user-attachments/files/16434055/click.ordering.repro.box.zip)
2. Click and drag the blue square

**Expected result:** The blue square moves around. It is the frontmost sprite.

**Actual result:** The red square moves around. This is unexpected since it's the backmost sprite &mdash; it's occluded by the blue square.

Here's a screenshot of the repro file:
<img width="330" alt="image" src="https://github.com/user-attachments/assets/36f60fe5-a0a0-4785-b064-af13a79f77ee">

# Potentially related issue
- #101

**Comment by sgithens** [comment]
Fixed in 2bc66924ec14a8f6246858004d3998e628dd0478 will be in v3.4.21

**Comment by sgithens** [comment]
Verified on v3.4.21 and closing.
