### ISSUE TITLE
Hidden (via `hideturtle`) receive click events

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#114]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`

1. Download, unzip, and open [hidden sprite repro.box.zip](https://github.com/user-attachments/files/16434116/hidden.sprite.repro.box.zip)
2. Click the middle of the graphics context. There's a large hidden (via `hideturtle`) rectangular sprite there

**Actual result:** The `output` box updates to say "Clicked sprite". This indicates the sprite's `mouse-down-on-sprite` handler has run. This is unexpected since the sprite is hidden

**Expected result:** The `output` box remains empty. The sprite's `mouse-down-on-sprite` handler hasn't run because the sprite is hidden.

Here's a screenshot of the repro file:
<img width="327" alt="image" src="https://github.com/user-attachments/assets/5e767323-5d35-43f3-9c08-9a377d675024">

**Comment by sgithens** [comment]
Fixed in 9ce6d7bd3c14b9f85cab9644f5a99d1fd7265828 will be in 3.4.21

**Comment by sgithens** [comment]
Verified on v3.4.21 and closing.
