### ISSUE TITLE
User Preferences Cleanup

### ISSUE THREAD

**Issue by sgithens** [boxer-project/boxer-sunrise#15]

**Comment by chaals** [comment]
In System-Preferences the last butlast and the last butlast butlast have the same description

> Display the toolbar on the boxer editor window?

but the apparent parameters are  BOXER-WINDOW-SHOW-STATUSBAR and BOXER-WINDOW-SHOW-TOOLBAR respectively.

Which is confusing

**Comment by sgithens** [comment]
Thanks @chaals .  I've updated the copy and pasted wording on that status bar preference!  Also, I believe the UPDATE-DISPLAY-DURING-EVAL may just end up being removed, but if not I'll try and see why it's displaying TRUE on new initializations.

**Comment by sgithens** [comment]
I'm considering the first round of this cleanup to be done. The Prefs auto-save now when you adjust them (removed the 'save set&save cancel' buttons)
