### ISSUE TITLE
Comprehensive JSON export

### ISSUE THREAD

**Issue by sgithens** [boxer-project/boxer-sunrise#3]
JSON Export with comprehensive details of box flags, graphics lists, etc etc.

**Comment by chaals** [comment]
JSON has issues dealing with mixing RTL and LTR text that Unicode doesn't solve. W3C has a *proposed* solution, or you can roll your own, or XML actually manages this.

**Comment by sgithens** [comment]
Huh.  At the moment there is the larger issue that Boxer doesn't support left to right language support yet, though I have thought about it a bit.

Do you have any suggested reading on the issues with JSON mixing these and the proposed solution?

**Comment by sgithens** [comment]
I'm closing this general purpose ticket, and will open a new one if any adjustments are needed to the export.
