### ISSUE TITLE
Mention compiled binaries ("Releases") in README.md

### ISSUE THREAD

**Issue by joshuahhh** [boxer-project/boxer-sunrise#32]
I spent some time trying to figure out how to compile this project (unsuccessfully) before realizing there were binaries available in the Releases section. I think it would be friendly if the README could link over to those releases somewhere prominent, if you think that's appropriate.

(Thank so much!)

**Comment by sgithens** [comment]
Hi @joshuahhh , thanks for the giving the docs a thorough read and taking the time to leave a note!  That's a good suggestion and I'll add this information to the README for sure.

I do agree that it's a bit difficult to agree to build at the moment, and hope to change that, though it will take some time.  In the meantime I am working to create builds every other month.  There were some issues in the last build with saving certain fonts, and am planning on another May build in a week or so for that and another hodgepodge of items.

**Comment by sgithens** [comment]
I've added to this to the top level readme:
https://github.com/boxer-project/boxer-sunrise/blob/master/README.md#release-downloads

Thanks again for the great suggestion.
