### ISSUE TITLE
Text is visible instead of clipped in manually-resized data box

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#74]
# Repro steps
I reproed this with Boxer `3.4.18 2024-05-26 ` on macOS

1. Create a data box
2. Type the numbers 1 thru 6 into it, one per line.
3. Manually resize the box so its height only fits the numbers 1 thru 3.

**Unexpected result:** The numbers at the bottom of the box (e.g. 4, 5, 6) should be clipped. Instead, they are visible.

![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/7e4e9a57-c87c-402b-81d5-fb7b09179753)

You can see the bug in this boxer file: [text clipping bug.box.zip](https://github.com/user-attachments/files/15570893/text.clipping.bug.box.zip)

**Comment by sgithens** [comment]
Oh, this is great thanks.  I think the math must be off for the fonts... or padding or something, since it does eventually clip and get scroll bars.  Much of this was reworked in this last build.

**Comment by sgithens** [comment]
This is largely fixed in 00b45722e84d0040d19f64e458c3cb5bf9d211f0 , although there is still some indirectly related work I'm doing for the sizing and math of the internal scrollbar that appears when the content is clipped.

Leaving open until it's verified against the upcoming 3.4.19 build.

**Comment by rigdern** [comment]
I verified this no longer repros in `3.4.19 2024-06-24`
