### ISSUE TITLE
Deletions *sometimes* affect paste behavior

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#78]
When deleting text within Boxer, the deleted text overwrites what's on the clipboard if the clipboard data came from Boxer but not if the clipboard data came from another app. At the very least, I think these paste behaviors should match. Ideally, I think we should pick the paste behavior that matches what typical macOS applications do. More details below.

(These tests were done with Boxer `3.4.18 2024-05-26` on macOS)

# Repro Steps A: Copying Text Within Boxer
1. Copy the text "copy me" in Boxer
2. Use the backspace key to delete the text "delete me" in Boxer
3. Paste

**Result:** The text "delete me" is pasted.

# Repro Steps B: Copying Text From Another App
1. Copy the text "copy me" in another macOS app such as TextEdit
2. Use the backspace key to delete the text "delete me" in Boxer
3. Paste

**Result:** The text "copy me" is pasted.

# Conclusions
- The paste behaviors in Repro Steps A & B should match but they currently do not.
- I prefer the behavior in Repro Steps B because it is consistent with how paste behaves in typical macOS applications. In the typical macOS application, the clipboard is only affected by copy & cut commands. It's never affected by deletions done by backspace.

**Comment by sgithens** [comment]
@rigdern Thanks for documenting this... I have some forthcoming notes on this, a lot of relates to our historical mimicings of certain emacs behaviors, including an emacs style killring.  My plan is to modernize this so the cut and paste works as you'd expect (including with other applications), and actually repurposing much of the killring/yank code to implement an initial set of undo functionality... something which most people immediately notice isn't available.

**Comment by sgithens** [comment]
I've done some initial work on this, enough to satisfy this ticket I believe and should be in the 3.4.20 build.  e19b676
Although I'd also like to make the cursor moving the end of what you've pasted on this round still.
Additionally, this included some initial kill buffer reorganization, creation of a paste buffer item, and ideally some direction towards some primitive undo/redo.  Leaving open until this is verified against 3.4.20.

**Comment by rigdern** [comment]
I confirmed this no longer repros in Boxer version `3.4.20 2024-08-06`
