### ISSUE TITLE
Graphics Boxes in "Vectors Demo" microworld are too small in build 3.4.18 2024-05-26

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#79]
# Repro steps
I reproed this with Boxer `3.4.18 2024-05-26` on macOS

1. Open the "Vectors Demo" microword file.
2. In Boxer, click the microwold's box to navigate into it.
3. Click the "Apollo Missions - Flight to the Moon" box to navigate into it.

**Unexpected result:** The graphics boxes are too small such that they look empty &mdash; their graphics are not visible. Specifically:
- Main graphics box. You should see a spaceship in this box but instead you see nothing.
- `vel` & `acc` boxes. You should see a dot in each of these (represents a zero vector) but instead you see nothing.

![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/70f40f36-fdbd-4741-a6f5-9d40b841c945)

**Expected result.** Here's how these 3 graphics boxes should look (screenshot from Boxer `3.4.16 2024-02-26`):
<img width="1278" alt="image" src="https://github.com/boxer-project/boxer-sunrise/assets/199935/9569df39-e4c1-4209-b942-b3b272df5c79">

# Impact
This impacts the "Vectors Demo" microworld.

**Comment by sgithens** [comment]
As hypothesized in #80, the same commit, 289f5cee443585cfb4a3b7047a631fdfa1af5e7c, has also fixed  this issue.

**Comment by rigdern** [comment]
I verified this no longer repros in `3.4.19 2024-06-24`
