### ISSUE TITLE
Shrinking a sprite causes stamp lines to disappear (impacts "Vectors Demo" microworld)

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#81]
# Repro steps
I reproed this with Boxer `3.4.18 2024-05-26` on macOS

1. Download [scaling sprites.box.zip](https://github.com/user-attachments/files/15877890/scaling.sprites.box.zip), unzip it, and open `scaling sprites.box`.
2. Click in the box named `scaling sprites` to view it.

**Unexpected result:** As the demo shows, the circles rendered by `stamp-hollow-circle` are partially clipped when `sprite-size` is `0.75` and are entirely invisible when `sprite-size` is `0.5`:

![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/72f135eb-caf9-403c-b9d0-edda6e10380d)

# Impact
This impacts the "Vectors Demo" microworld. The Earth is missing its border.

Repro steps:
1. Open the "Vectors Demo" microword file.
2. In Boxer, click the microwold's box to navigate into it.
3. Click the "Apollo Missions - Flight to the Moon" box to navigate into it.
4. Click "earth-orbit" in the "menu" box to view that scenario.

**Unexpected result:** The Earth is missing its border (the `sprite-size` is `0.5`) (to see any graphics at all, you might have to resize the graphics box due to issue #79):
![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/81bb5560-c7dd-4d0d-b4ab-5f6040468e70)

**Workaround.** As a workaround to see the Earth with a border, change its `sprite-size` to `1` by running: `tell earth set-sprite-size 1`:
![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/6beb1525-7198-4547-91af-71680de02d92)

**Comment by sgithens** [comment]
I think this may be related to an issue with a GL Shader I wrote for circles/ellipses, and likely also affects rotating/app-zooming.  Looking in to it...

**Comment by sgithens** [comment]
This is actually fixed in 3.4.21 now as a result of the other related sprite/graphics rendering work.
