### ISSUE TITLE
`setshape` to a graphics box fails with Common Lisp exception: Undefined function `BOXER::MAKE-BOXER-GRAPHICS-COMMAND-CENTERED-BITMAP`

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#84]
# Repro steps
I reproed this with Boxer `3.4.18 2024-05-26`

1. Download [setshape to a graphics box.box.zip](https://github.com/user-attachments/files/15931524/setshape.to.a.graphics.box.box.zip)
2. Open "setshape to a graphics box.box" in Boxer
3. Run this line at the bottom of the file: `tell planet-sprite setshape 🌎` (🌎 represents a graphics box)

**Unexpected result:** It fails with a Common Lisp exception: `Undefined function BOXER::MAKE-BOXER-GRAPHICS-COMMAND-CENTERED-BITMAP called with arguments (#<BOXER::OGL-PIXMAP 801007F92B> 0 0 175 178)`

Here's a screenshot of the box:
![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/e402c397-5045-4b13-aebb-635c3629edfc)

# Workaround?
If anyone is aware of a workaround for this, let me know.

**Comment by sgithens** [comment]
Thanks for posting this, I thought it was fixed (it's popped up once before), but will take another look with your test case.

**Comment by sgithens** [comment]
This is fixed now and will be in next weeks build. a749c5bbf7768ac902d8ebfbcde65e6736e6d7e2

**Comment by rigdern** [comment]
I verified this no longer repros in `3.4.19 2024-06-24`
