### ISSUE TITLE
Sprite's `SHAPE` & `SHOWN?` boxes render on top of each other

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#87]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`. It **does not** repro with `3.4.18 2024-05-26`.

1. Create a new sprite.
2. Click into the sprite and open its closet
3. Evaluate `Show-Sprite-Properties`

**Unexpected result:** The `SHAPE` box renders on top of the `SHOWN?` box. Screenshot:
![image](https://github.com/boxer-project/boxer-sunrise/assets/199935/d35499ba-0a30-40ba-8229-ac35294aa66f)

**Comment by sgithens** [comment]
Oof, thanks for filing this, I noticed it earlier today (maybe yesterday), and it is frightenfully annoying. 

In the new layout, I must be leaving out the check to make the minimum box width take in to account the length of the name label.  Hope to have this one fixed shortly.

**Comment by sgithens** [comment]
This is fixed now with d162869 . Leaving ticket open until it's included in the 3.4.20 build.

**Comment by rigdern** [comment]
I confirmed this no longer repros in Boxer version `3.4.20 2024-08-06`
