### ISSUE TITLE
graphics `stamp` at `(0, 0)` instead of at the turtle's coordinates

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#92]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`.

1. Download [stamp a picture.box.zip](https://github.com/user-attachments/files/16043080/stamp.a.picture.box.zip), unzip it, and open it.
2. Run `cs` to clear the screen.
3. Run `run-me` to stamp the picture.

**Expected result:** `picture` is stamped at `(80, 80)`.

**Actual result:** `picture`'s foreground is incorrectly stamped at `(0, 0)`. Interestingly, it looks like its green background is correctly stamped at `(80, 80)`. Screenshot:
<img width="320" alt="image" src="https://github.com/boxer-project/boxer-sunrise/assets/199935/647465f3-c3f8-4681-a5e3-bb68d9682882">

**Comment by sgithens** [comment]
This is fixed now in a5f3eee , and will be in the 3.4.20 build.  Leaving ticket open until we verify it in the build.

**Comment by rigdern** [comment]
I confirmed this no longer repros in Boxer version `3.4.20 2024-08-06`
